### ISSUE TITLE
pip installation isn't working

### ISSUE THREAD

**Issue by auvipy** [Seedstars/django-rest-logger#1]
pip3 install django-rest-logger
The directory '/home/asif/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/asif/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting django-rest-logger
  Could not find a version that satisfies the requirement django-rest-logger (from versions: )
No matching distribution found for django-rest-logger

**Comment by camspilly** [comment]
If your python is  > 3.4, it may not be compatible. The README states it's listed for just 2.7, 3.3, 3.4

**Comment by denizdogan** [comment]
Any plans on supporting 3.5 and 3.6? It's been a while :)
